### PR TITLE
Fix compile issues due to duplicate symbols

### PR DESCRIPTION
**Pull request by lambdanature**
Tested on:
  - Ubuntu 22.04.3 LTS, gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  - Debian GNU/Linux 12 (bookworm), gcc (Debian 12.2.0-14) 12.2.0
  - MacOS Sonoma 14.1.2 (23B92), Apple clang version 15.0.0 (clang-1500.1.0.2.5)

### CODE REVIEW

**Comment by algodesigner** [comment]
How can I reproduce this issue? I am very keen to. It compiles fine in all of my current environments (MINGw64, Mac OS, Ubuntu)

**Comment by 61131** [comment]
I can confirm this PR/branch as working on Ubuntu 24.04.1, gcc 13.3.0 and Alpine 3.18.4, gcc 12.2.1.

**Comment by algodesigner** [comment]
@lambdanature Thank you very much for the fix. Tested and merged. Happy New Year!
